name: workshop-pysal-wrsa24
channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.11
  - mamba
  - bokeh
  - pip
  - geopandas
  - descartes
  - folium
  - ipywidgets
  - jupyterlab
  - pysal
  - nbconvert
  - numpy <= 1.24
  - numba ==0.57
  - networkx
  - scikit-learn
  - seaborn
  - statsmodels
  - hvplot
  - holoviews
  - geoviews
  - watermark
  - rasterio
  - contextily
  - geosnap
  - scipy <= 1.11
